In [1]:
import pandas as pd

In [2]:
fifa_train_x = pd.read_csv("data/연습문제/FIFA_X_train.csv", encoding='CP949')

In [3]:
fifa_train_y = pd.read_csv("data/연습문제/FIFA_Y_train.csv", encoding='CP949')

In [4]:
fifa_test_x = pd.read_csv("data/연습문제/FIFA_X_test.csv", encoding='CP949')

In [5]:
fifa_test_y = pd.read_csv("data/연습문제/FIFA_Y_test.csv", encoding='CP949')

In [6]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170.0,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180.0,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175.0,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175.0,132.0,578,1

In [7]:
fifa_train_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class          758
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               292
Weight_lb                72
Release_Clause            0
Wage                      0
dtype: int64

In [8]:
#Position_Class 결측치 처리

In [9]:
def handle_mission_position_class(df):
    total_position = set(df.Position.unique())
    defender = set(pd.Series(df.Position.unique()).loc[pd.Series(df.Position.unique()).apply(lambda x: x.endswith(("B","DM")))])
    GK=set(["GK"])
    sub_position = total_position-defender-GK
    midfielder = set(pd.Series(list(sub_position)).loc[pd.Series(list(sub_position)).apply(lambda x: x.endswith("M"))])
    forward = sub_position - midfielder - GK
    df.loc[df.Position.isin(forward), "Position_Class"] = "Forward"
    df.loc[df.Position.isin(GK), "Position_Class"] = "GoalKeeper"
    df.loc[df.Position.isin(midfielder), "Position_Class"] = "Midfielder"
    df.loc[df.Position.isin(defender), "Position_Class"] = "Defender"

In [10]:
handle_mission_position_class(fifa_train_x)

In [11]:
fifa_train_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               292
Weight_lb                72
Release_Clause            0
Wage                      0
dtype: int64

In [12]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class          509
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [13]:
handle_mission_position_class(fifa_test_x)

In [14]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [15]:
#########################################

In [16]:
#Height_cm 결측치 처리

In [17]:
def handle_mission_height_cm(df):
    Height_feet_list = df.Height.loc[df.Height_cm.isna()].unique()
#     print(Height_feet_list)
    result = []
    for x in Height_feet_list:
#         print(df.Height_cm.loc[df.Height==x])
#         print(df.Height_cm.loc[df.Height==x].mode())
        result.append(df.Height_cm.loc[df.Height==x].mode().values)
#     print(result)
    df_height_missing_value = pd.DataFrame()
    df_height_missing_value["Height_cm"] = result
    df_height_missing_value["Height"] = Height_feet_list
#     display(df.loc[df.Height_cm.isna(),["Height","Height_cm"]])
    df_height_missing_value\
       .loc[df_height_missing_value["Height"]==df.Height.loc[16],"Height_cm"].values
    df_height_cm_missing = df.loc[df.Height_cm.isna(),["Height","Height_cm"]]\
    .apply(lambda x: df_height_missing_value\
           .loc[df_height_missing_value["Height"]==x["Height"],"Height_cm"].values[0], axis=1)
#     display(df.Height_cm)
#     display(df_height_cm_missing)
#     display(df_height_cm_missing.index)
#     display(df_height_cm_missing.values)
    df.loc[df_height_cm_missing.index,"Height_cm"] = df_height_cm_missing
    return df

In [18]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170.0,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180.0,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175.0,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175.0,132.0,578,1

In [19]:
fifa_train_x = handle_mission_height_cm(fifa_train_x)

In [20]:
fifa_train_x.isna().sum()

ID                       0
Age                      0
Nationality              0
Overall                  0
Club                     0
Preferred_Foot           0
Work_Rate                0
Position                 0
Position_Class           0
Jersey_Number            0
Contract_Valid_Until     0
Height                   0
Height_cm                0
Weight_lb               72
Release_Clause           0
Wage                     0
dtype: int64

In [21]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [22]:
fifa_test_x = handle_mission_height_cm(fifa_test_x)

In [23]:
fifa_test_x.isna().sum()

ID                      0
Age                     0
Nationality             0
Overall                 0
Club                    0
Preferred_Foot          0
Work_Rate               0
Position                0
Position_Class          0
Jersey_Number           0
Contract_Valid_Until    0
Height                  0
Height_cm               0
Weight_lb               0
Release_Clause          0
Wage                    0
dtype: int64

In [24]:
#########################################

In [25]:
#Weight_lb 결측치 처리

In [26]:
def handle_missing(data, ps_class, param):
    return data.loc[data.Position_Class==ps_class,param]\
    .fillna(data.loc[data.Position_Class==ps_class,param].mean(skipna=True))

In [27]:
def handle_mission_weight_lb(df):
    for position_class in df.Position_Class.unique():
        df.loc[df.Position_Class==position_class,"Weight_lb"] = handle_missing(df,position_class,"Weight_lb")
    return df

In [28]:
handle_mission_weight_lb(fifa_train_x)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,23,Croatia,64,Dinamo Zagreb,Left,Medium/ Medium,CB,Defender,55,2022,6'6,195,185.0,1100,1
3596,201891,28,Austria,65,TSV Hartberg,Right,Medium/ Medium,ST,Forward,24,2020,5'10,175,170.0,798,3
3597,241918,23,Norway,58,Ranheim Fotball,Right,High/ Medium,ST,Forward,14,2019,6'0,180,163.0,225,1
3598,186823,33,Portugal,65,CD Aves,Right,Medium/ Medium,RB,Defender,17,2019,5'10,175,161.0,441,3
3599,240328,22,Saudi Arabia,58,Al Fayha,Left,Medium/ Medium,LWB,Defender,24,2021,5'10,175,154.0,315,2

In [29]:
fifa_train_x.isna().sum()

ID                      0
Age                     0
Nationality             0
Overall                 0
Club                    0
Preferred_Foot          0
Work_Rate               0
Position                0
Position_Class          0
Jersey_Number           0
Contract_Valid_Until    0
Height                  0
Height_cm               0
Weight_lb               0
Release_Clause          0
Wage                    0
dtype: int64

In [30]:
#########################################

In [31]:
#Age 데이터 처리

In [32]:
def age_mean_without_star(df, str_number):
    temp = df.Age.loc[df.Age.apply(lambda x: (x.startswith(str_number)))]
    return int(round(temp.loc[temp.apply(lambda x: not x.endswith(('*')))].astype('int32').mean(),0))

In [33]:
def handle_mission_age(df):
    unique_wrong_number_list = df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].unique()
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())]
    unique_wrong_number_mean_list = [age_mean_without_star(df,x[0]) for x in unique_wrong_number_list]
    unique_wrong_number_mean_list.sort()
    
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].apply(lambda x: unique_wrong_number_mean_list[int(x[0])-1])
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())] =df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].apply(lambda x: unique_wrong_number_mean_list[int(x[0])-1])
    df.Age=df.Age.astype('int32')

In [34]:
fifa_train_x.Age.unique()

array(['2*', '29', '23', '22', '18', '19', '30', '24', '20', '21', '17',
       '35', '28', '3*', '32', '25', '31', '26', '27', '1*', '16', '34',
       '38', '33', '36', '37', '42', '39', '41'], dtype=object)

In [35]:
handle_mission_age(fifa_train_x)

C:\Users\yuvjj\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [36]:
fifa_train_x.Age.unique()

array([24, 29, 23, 22, 18, 19, 30, 20, 21, 17, 35, 28, 32, 25, 31, 26, 27,
       16, 34, 38, 33, 36, 37, 42, 39, 41], dtype=int64)

In [37]:
fifa_test_x.Age.unique()

array(['34', '29', '22', '25', '2*', '31', '3*', '21', '20', '26', '19',
       '23', '1*', '24', '27', '17', '28', '30', '32', '33', '18', '36',
       '35', '37', '16', '38', '4*', '39', '41', '40', '45'], dtype=object)

In [38]:
handle_mission_age(fifa_test_x)

In [39]:
fifa_test_x.Age.unique()

array([34, 29, 22, 25, 24, 31, 32, 21, 20, 26, 19, 23, 18, 27, 17, 28, 30,
       33, 36, 35, 37, 16, 38, 42, 39, 41, 40, 45], dtype=int64)

In [40]:
#######################################

In [41]:
####Wokr_Rate 분리

In [42]:
def handle_work_rate(df):
    df["Attack_Work_Rate"] = df.Work_Rate.apply(lambda x:x.split('/')[0].strip())
    df["Defence_Work_Rate"] = df.Work_Rate.apply(lambda x:x.split('/')[1].strip())

In [43]:
handle_work_rate(fifa_train_x)

In [44]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,24,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19,High,Medium
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4,High,Medium
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2,High,Low
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1,Medium,Medium
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1,High,Low

In [45]:
handle_work_rate(fifa_test_x)

In [46]:
fifa_test_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,34,Germany,79,FC Augsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,172.5,172,6500,28,Medium,High
1,207707,29,Brazil,77,Olympique Lyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,175,163,12400,54,Medium,Medium
2,242101,22,Korea Republic,64,Pohang Steelers,Right,High/ Medium,RW,Forward,18,2021,6'1,182.5,170,1000,2,High,Medium
3,200104,25,Korea Republic,84,Tottenham Hotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,180,143,71200,125,High,High
4,244229,24,Italy,66,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,[185.0],170,1400,1,Medium,Medium

In [47]:
fifa_test_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,34,Germany,79,FC Augsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,172.5,172,6500,28,Medium,High
1,207707,29,Brazil,77,Olympique Lyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,175,163,12400,54,Medium,Medium
2,242101,22,Korea Republic,64,Pohang Steelers,Right,High/ Medium,RW,Forward,18,2021,6'1,182.5,170,1000,2,High,Medium
3,200104,25,Korea Republic,84,Tottenham Hotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,180,143,71200,125,High,High
4,244229,24,Italy,66,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,[185.0],170,1400,1,Medium,Medium

In [48]:
##############
###Club handle

In [49]:
import re

In [50]:
fifa_train_x.Club = fifa_train_x.Club.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [51]:
fifa_test_x.Club = fifa_test_x.Club.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [52]:
#############
####Nationality handle

In [53]:
fifa_train_x.Nationality = fifa_train_x.Nationality.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [54]:
fifa_test_x.Nationality = fifa_test_x.Nationality.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [55]:
####
#변수 정리

In [56]:
####
#수치형 변수 scaling

In [57]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,24,Argentina,81,SLBenfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19,High,Medium
1,179646,29,Denmark,66,AarhusGF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4,High,Medium
2,225440,23,GuineaBissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2,High,Low
3,212642,22,Sweden,61,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1,Medium,Medium
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1,High,Low

In [58]:
fifa_train_x.columns

Index(['ID', 'Age', 'Nationality', 'Overall', 'Club', 'Preferred_Foot',
       'Work_Rate', 'Position', 'Position_Class', 'Jersey_Number',
       'Contract_Valid_Until', 'Height', 'Height_cm', 'Weight_lb',
       'Release_Clause', 'Wage', 'Attack_Work_Rate', 'Defence_Work_Rate'],
      dtype='object')

In [59]:
col_num = ['Age','Overall','Height_cm','Release_Clause', 'Wage']

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
def numeric_scaling(df, col):
    df.loc[:,col_num] = StandardScaler().fit_transform(X=df.loc[:,col])
    return df

In [62]:
numeric_scaling(fifa_train_x,col_num)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,Right,High/ Medium,RW,Forward,18,2019,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,Left,High/ Medium,LCB,Defender,18,2019,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,Left,Medium/ Medium,CB,Defender,55,2022,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,Right,Medium/ Medium,ST,Forward,24,2020,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,Right,High/ Medium,ST,Forward,14,2019,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,Right,Medium/ Medium,RB,Defender,17,2019,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,Left,Medium/ Medium,LWB,Defender,24,2021,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [63]:
numeric_scaling(fifa_test_x,col_num)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,-0.867562,172,0.135107,0.697853,Medium,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,-0.491383,163,0.603083,1.715902,Medium,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,Right,High/ Medium,RW,Forward,18,2021,6'1,0.637152,170,-0.301141,-0.320196,High,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,0.260974,143,5.266978,4.495960,High,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,1.013331,170,-0.269414,-0.359352,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,Right,Medium/ Low,LM,Midfielder,11,2020,5'11,-0.115205,172,0.190630,0.502074,Medium,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,Right,Medium/ Medium,CDM,Defender,14,2019,5'11,-0.115205,143,-0.364754,-0.320196,Medium,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,Right,Medium/ Medium,RB,Defender,54,2019,5'10,-0.491383,154,-0.354443,-0.241885,Medium,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,Right,High/ Low,LM,Midfielder,31,2019,5'9,-0.867562,174,-0.134573,-0.006950,High,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,Right,Medium/ Medium,LM,Midfielder,18,2021,5'6,-1.996097,137,-0.158369,-0.046106,Medium,Medium

In [64]:
###
#명목형 데이터 labeling

In [65]:
fifa_train_x.Contract_Valid_Until.unique()

array([2019, 2020, 2022, 2021, 2018, 2023, 2024, 2025, 2026], dtype=int64)

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
def label_encoding(df, param):
    le = LabelEncoder()
    df.loc[:,param] = le.fit_transform(df.loc[:,param])
    return df

In [68]:
label_encoding(fifa_train_x, "Contract_Valid_Until")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,Right,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,Left,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,Left,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,Right,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,Left,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,Right,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,Right,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,Right,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,Left,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [69]:
label_encoding(fifa_test_x, "Contract_Valid_Until")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,Right,Medium/ High,CDM,Defender,10,1,5'9,-0.867562,172,0.135107,0.697853,Medium,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,Left,Medium/ Medium,LB,Defender,20,3,5'10,-0.491383,163,0.603083,1.715902,Medium,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,Right,High/ Medium,RW,Forward,18,3,6'1,0.637152,170,-0.301141,-0.320196,High,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,Right,High/ High,LM,Midfielder,7,5,6'0,0.260974,143,5.266978,4.495960,High,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,Right,Medium/ Medium,CB,Defender,15,2,6'2,1.013331,170,-0.269414,-0.359352,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,Right,Medium/ Low,LM,Midfielder,11,2,5'11,-0.115205,172,0.190630,0.502074,Medium,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,Right,Medium/ Medium,CDM,Defender,14,1,5'11,-0.115205,143,-0.364754,-0.320196,Medium,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,Right,Medium/ Medium,RB,Defender,54,1,5'10,-0.491383,154,-0.354443,-0.241885,Medium,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,Right,High/ Low,LM,Midfielder,31,1,5'9,-0.867562,174,-0.134573,-0.006950,High,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,Right,Medium/ Medium,LM,Midfielder,18,3,5'6,-1.996097,137,-0.158369,-0.046106,Medium,Medium

In [70]:
label_encoding(fifa_test_x, "Preferred_Foot")
label_encoding(fifa_train_x, "Preferred_Foot")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [71]:
##work_rate handle

In [72]:
def handle_work_rate(df, param):
    df.loc[:,param] = df.loc[:,param].apply(lambda x: 2 if x=="High" else (1 if x=="Medium" else (0 if x=="Low" else x)))
    return df

In [73]:
fifa_train_x.Attack_Work_Rate.value_counts()

Medium    2426
High       997
Low        177
Name: Attack_Work_Rate, dtype: int64

In [74]:
handle_work_rate(fifa_train_x, "Attack_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,2,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,2,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,2,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,1,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,2,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,1,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,1,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,2,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,1,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,1,Medium

In [75]:
fifa_train_x.Attack_Work_Rate.value_counts()

1    2426
2     997
0     177
Name: Attack_Work_Rate, dtype: int64

In [76]:
fifa_test_x.Attack_Work_Rate.value_counts()

Medium    1634
High       663
Low        103
Name: Attack_Work_Rate, dtype: int64

In [77]:
handle_work_rate(fifa_test_x, "Attack_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,1,Medium/ High,CDM,Defender,10,1,5'9,-0.867562,172,0.135107,0.697853,1,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,0,Medium/ Medium,LB,Defender,20,3,5'10,-0.491383,163,0.603083,1.715902,1,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,1,High/ Medium,RW,Forward,18,3,6'1,0.637152,170,-0.301141,-0.320196,2,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,1,High/ High,LM,Midfielder,7,5,6'0,0.260974,143,5.266978,4.495960,2,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,1,Medium/ Medium,CB,Defender,15,2,6'2,1.013331,170,-0.269414,-0.359352,1,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,1,Medium/ Low,LM,Midfielder,11,2,5'11,-0.115205,172,0.190630,0.502074,1,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,1,Medium/ Medium,CDM,Defender,14,1,5'11,-0.115205,143,-0.364754,-0.320196,1,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,1,Medium/ Medium,RB,Defender,54,1,5'10,-0.491383,154,-0.354443,-0.241885,1,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,1,High/ Low,LM,Midfielder,31,1,5'9,-0.867562,174,-0.134573,-0.006950,2,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,1,Medium/ Medium,LM,Midfielder,18,3,5'6,-1.996097,137,-0.158369,-0.046106,1,Medium

In [78]:
fifa_test_x.Attack_Work_Rate.value_counts()

1    1634
2     663
0     103
Name: Attack_Work_Rate, dtype: int64

In [79]:
handle_work_rate(fifa_test_x, "Defence_Work_Rate")
handle_work_rate(fifa_train_x, "Defence_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,2,1
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,2,1
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,2,0
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,1,1
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,1,1
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,1,1
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,2,1
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,1,1
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,1,1

In [85]:
#one hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
OneHotEncoder()

In [80]:
#변수 정리

In [81]:
drop_col = ['Nationality', 'Jersey_Number', 'Club', 'ID','Work_Rate', "Height"]

In [82]:
fifa_train_x.drop(columns=drop_col)

,Age,Overall,Preferred_Foot,Position,Position_Class,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,-0.251299,2.156933,1,RW,Forward,1,-1.276671,170.0,3.261035,0.493504,2,1
1,0.830590,-0.016299,0,LCB,Defender,1,0.251133,179.0,-0.379257,-0.271619,2,1
2,-0.467677,0.273465,0,LW,Forward,2,-0.894720,163.0,-0.241652,-0.373635,2,0
3,-0.684055,-0.740710,1,LW,Forward,2,-0.512769,154.0,-0.398672,-0.424643,1,1
4,-1.549566,-1.320238,1,ST,Forward,4,-0.512769,132.0,-0.383961,-0.424643,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3595,-0.467677,-0.306064,0,CB,Defender,4,2.542839,185.0,-0.331721,-0.424643,1,1
3596,0.614213,-0.161181,1,ST,Forward,2,-0.512769,170.0,-0.361944,-0.322627,1,1
3597,-0.467677,-1.175356,1,ST,Forward,1,0.251133,163.0,-0.419288,-0.424643,2,1
3598,1.696102,-0.161181,1,RB,Defender,1,-0.512769,161.0,-0.397672,-0.322627,1,1
3599,-0.684055,-1.175356,0,LWB,Defender,3,-0.512769,154.0,-0.410281,-0.373635,1,1