In [1]:
import pandas as pd

In [2]:
fifa_train_x = pd.read_csv("data/연습문제/FIFA_X_train.csv", encoding='CP949')

In [3]:
fifa_train_y = pd.read_csv("data/연습문제/FIFA_Y_train.csv", encoding='CP949')

In [4]:
fifa_test_x = pd.read_csv("data/연습문제/FIFA_X_test.csv", encoding='CP949')

In [5]:
fifa_test_y = pd.read_csv("data/연습문제/FIFA_Y_test.csv", encoding='CP949')

In [6]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170.0,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180.0,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175.0,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175.0,132.0,578,1

In [7]:
fifa_train_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class          758
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               292
Weight_lb                72
Release_Clause            0
Wage                      0
dtype: int64

In [8]:
#Position_Class 결측치 처리

In [9]:
def handle_mission_position_class(df):
    total_position = set(df.Position.unique())
    defender = set(pd.Series(df.Position.unique()).loc[pd.Series(df.Position.unique()).apply(lambda x: x.endswith(("B","DM")))])
    GK=set(["GK"])
    sub_position = total_position-defender-GK
    midfielder = set(pd.Series(list(sub_position)).loc[pd.Series(list(sub_position)).apply(lambda x: x.endswith("M"))])
    forward = sub_position - midfielder - GK
    df.loc[df.Position.isin(forward), "Position_Class"] = "Forward"
    df.loc[df.Position.isin(GK), "Position_Class"] = "GoalKeeper"
    df.loc[df.Position.isin(midfielder), "Position_Class"] = "Midfielder"
    df.loc[df.Position.isin(defender), "Position_Class"] = "Defender"

In [10]:
handle_mission_position_class(fifa_train_x)

In [11]:
fifa_train_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               292
Weight_lb                72
Release_Clause            0
Wage                      0
dtype: int64

In [12]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class          509
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [13]:
handle_mission_position_class(fifa_test_x)

In [14]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [15]:
#########################################

In [16]:
#Height_cm 결측치 처리

In [17]:
def handle_mission_height_cm(df):
    Height_feet_list = df.Height.loc[df.Height_cm.isna()].unique()
#     print(Height_feet_list)
    result = []
    for x in Height_feet_list:
#         print(df.Height_cm.loc[df.Height==x])
#         print(df.Height_cm.loc[df.Height==x].mode())
        result.append(df.Height_cm.loc[df.Height==x].mode().values)
#     print(result)
    df_height_missing_value = pd.DataFrame()
    df_height_missing_value["Height_cm"] = result
    df_height_missing_value["Height"] = Height_feet_list
#     display(df.loc[df.Height_cm.isna(),["Height","Height_cm"]])
    df_height_missing_value\
       .loc[df_height_missing_value["Height"]==df.Height.loc[16],"Height_cm"].values
    df_height_cm_missing = df.loc[df.Height_cm.isna(),["Height","Height_cm"]]\
    .apply(lambda x: df_height_missing_value\
           .loc[df_height_missing_value["Height"]==x["Height"],"Height_cm"].values[0], axis=1)
#     display(df.Height_cm)
#     display(df_height_cm_missing)
#     display(df_height_cm_missing.index)
#     display(df_height_cm_missing.values)
    df.loc[df_height_cm_missing.index,"Height_cm"] = df_height_cm_missing
    return df

In [18]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170.0,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180.0,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175.0,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175.0,132.0,578,1

In [19]:
fifa_train_x = handle_mission_height_cm(fifa_train_x)

In [20]:
fifa_train_x.isna().sum()

ID                       0
Age                      0
Nationality              0
Overall                  0
Club                     0
Preferred_Foot           0
Work_Rate                0
Position                 0
Position_Class           0
Jersey_Number            0
Contract_Valid_Until     0
Height                   0
Height_cm                0
Weight_lb               72
Release_Clause           0
Wage                     0
dtype: int64

In [21]:
fifa_test_x.isna().sum()

ID                        0
Age                       0
Nationality               0
Overall                   0
Club                      0
Preferred_Foot            0
Work_Rate                 0
Position                  0
Position_Class            0
Jersey_Number             0
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64

In [22]:
fifa_test_x = handle_mission_height_cm(fifa_test_x)

In [23]:
fifa_test_x.isna().sum()

ID                      0
Age                     0
Nationality             0
Overall                 0
Club                    0
Preferred_Foot          0
Work_Rate               0
Position                0
Position_Class          0
Jersey_Number           0
Contract_Valid_Until    0
Height                  0
Height_cm               0
Weight_lb               0
Release_Clause          0
Wage                    0
dtype: int64

In [24]:
#########################################

In [25]:
#Weight_lb 결측치 처리

In [26]:
def handle_missing(data, ps_class, param):
    return data.loc[data.Position_Class==ps_class,param]\
    .fillna(data.loc[data.Position_Class==ps_class,param].mean(skipna=True))

In [27]:
def handle_mission_weight_lb(df):
    for position_class in df.Position_Class.unique():
        df.loc[df.Position_Class==position_class,"Weight_lb"] = handle_missing(df,position_class,"Weight_lb")
    return df

In [28]:
handle_mission_weight_lb(fifa_train_x)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage
0,190972,2*,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,23,Croatia,64,Dinamo Zagreb,Left,Medium/ Medium,CB,Defender,55,2022,6'6,195,185.0,1100,1
3596,201891,28,Austria,65,TSV Hartberg,Right,Medium/ Medium,ST,Forward,24,2020,5'10,175,170.0,798,3
3597,241918,23,Norway,58,Ranheim Fotball,Right,High/ Medium,ST,Forward,14,2019,6'0,180,163.0,225,1
3598,186823,33,Portugal,65,CD Aves,Right,Medium/ Medium,RB,Defender,17,2019,5'10,175,161.0,441,3
3599,240328,22,Saudi Arabia,58,Al Fayha,Left,Medium/ Medium,LWB,Defender,24,2021,5'10,175,154.0,315,2

In [29]:
fifa_train_x.isna().sum()

ID                      0
Age                     0
Nationality             0
Overall                 0
Club                    0
Preferred_Foot          0
Work_Rate               0
Position                0
Position_Class          0
Jersey_Number           0
Contract_Valid_Until    0
Height                  0
Height_cm               0
Weight_lb               0
Release_Clause          0
Wage                    0
dtype: int64

In [30]:
#########################################

In [31]:
#Age 데이터 처리

In [32]:
def age_mean_without_star(df, str_number):
    temp = df.Age.loc[df.Age.apply(lambda x: (x.startswith(str_number)))]
    return int(round(temp.loc[temp.apply(lambda x: not x.endswith(('*')))].astype('int32').mean(),0))

In [33]:
def handle_mission_age(df):
    unique_wrong_number_list = df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].unique()
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())]
    unique_wrong_number_mean_list = [age_mean_without_star(df,x[0]) for x in unique_wrong_number_list]
    unique_wrong_number_mean_list.sort()
    
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].apply(lambda x: unique_wrong_number_mean_list[int(x[0])-1])
    df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())] =df.Age.loc[~df.Age.apply(lambda x: x.isdecimal())].apply(lambda x: unique_wrong_number_mean_list[int(x[0])-1])
    df.Age=df.Age.astype('int32')

In [34]:
fifa_train_x.Age.unique()

array(['2*', '29', '23', '22', '18', '19', '30', '24', '20', '21', '17',
       '35', '28', '3*', '32', '25', '31', '26', '27', '1*', '16', '34',
       '38', '33', '36', '37', '42', '39', '41'], dtype=object)

In [35]:
handle_mission_age(fifa_train_x)

C:\Users\yuvjj\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [36]:
fifa_train_x.Age.unique()

array([24, 29, 23, 22, 18, 19, 30, 20, 21, 17, 35, 28, 32, 25, 31, 26, 27,
       16, 34, 38, 33, 36, 37, 42, 39, 41], dtype=int64)

In [37]:
fifa_test_x.Age.unique()

array(['34', '29', '22', '25', '2*', '31', '3*', '21', '20', '26', '19',
       '23', '1*', '24', '27', '17', '28', '30', '32', '33', '18', '36',
       '35', '37', '16', '38', '4*', '39', '41', '40', '45'], dtype=object)

In [38]:
handle_mission_age(fifa_test_x)

In [39]:
fifa_test_x.Age.unique()

array([34, 29, 22, 25, 24, 31, 32, 21, 20, 26, 19, 23, 18, 27, 17, 28, 30,
       33, 36, 35, 37, 16, 38, 42, 39, 41, 40, 45], dtype=int64)

In [40]:
#######################################

In [41]:
####Wokr_Rate 분리

In [42]:
def handle_work_rate(df):
    df["Attack_Work_Rate"] = df.Work_Rate.apply(lambda x:x.split('/')[0].strip())
    df["Defence_Work_Rate"] = df.Work_Rate.apply(lambda x:x.split('/')[1].strip())

In [43]:
handle_work_rate(fifa_train_x)

In [44]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,24,Argentina,81,SL Benfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19,High,Medium
1,179646,29,Denmark,66,Aarhus GF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4,High,Medium
2,225440,23,Guinea Bissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2,High,Low
3,212642,22,Sweden,61,IF Brommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1,Medium,Medium
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1,High,Low

In [45]:
handle_work_rate(fifa_test_x)

In [46]:
fifa_test_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,34,Germany,79,FC Augsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,172.5,172,6500,28,Medium,High
1,207707,29,Brazil,77,Olympique Lyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,175,163,12400,54,Medium,Medium
2,242101,22,Korea Republic,64,Pohang Steelers,Right,High/ Medium,RW,Forward,18,2021,6'1,182.5,170,1000,2,High,Medium
3,200104,25,Korea Republic,84,Tottenham Hotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,180,143,71200,125,High,High
4,244229,24,Italy,66,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,[185.0],170,1400,1,Medium,Medium

In [47]:
fifa_test_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,34,Germany,79,FC Augsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,172.5,172,6500,28,Medium,High
1,207707,29,Brazil,77,Olympique Lyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,175,163,12400,54,Medium,Medium
2,242101,22,Korea Republic,64,Pohang Steelers,Right,High/ Medium,RW,Forward,18,2021,6'1,182.5,170,1000,2,High,Medium
3,200104,25,Korea Republic,84,Tottenham Hotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,180,143,71200,125,High,High
4,244229,24,Italy,66,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,[185.0],170,1400,1,Medium,Medium

In [48]:
##############
###Club handle

In [49]:
import re

In [50]:
fifa_train_x.Club = fifa_train_x.Club.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [51]:
fifa_test_x.Club = fifa_test_x.Club.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [52]:
#############
####Nationality handle

In [53]:
fifa_train_x.Nationality = fifa_train_x.Nationality.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [54]:
fifa_test_x.Nationality = fifa_test_x.Nationality.apply(lambda x: re.sub(r"[^0-9a-zA-Z]","",x))

In [55]:
####
#변수 정리

In [56]:
####
#수치형 변수 scaling

In [57]:
fifa_train_x.head()

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,24,Argentina,81,SLBenfica,Right,High/ Medium,RW,Forward,18,2019,5'8,170,170.0,37000,19,High,Medium
1,179646,29,Denmark,66,AarhusGF,Left,High/ Medium,LCB,Defender,18,2019,6'0,180,179.0,625,4,High,Medium
2,225440,23,GuineaBissau,68,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,172.5,163.0,2000,2,High,Low
3,212642,22,Sweden,61,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,175,154.0,431,1,Medium,Medium
4,245804,18,Turkey,57,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,175,132.0,578,1,High,Low

In [58]:
fifa_train_x.columns

Index(['ID', 'Age', 'Nationality', 'Overall', 'Club', 'Preferred_Foot',
       'Work_Rate', 'Position', 'Position_Class', 'Jersey_Number',
       'Contract_Valid_Until', 'Height', 'Height_cm', 'Weight_lb',
       'Release_Clause', 'Wage', 'Attack_Work_Rate', 'Defence_Work_Rate'],
      dtype='object')

In [59]:
col_num = ['Age','Overall','Height_cm','Release_Clause', 'Wage']

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
def numeric_scaling(df, col):
    df.loc[:,col_num] = StandardScaler().fit_transform(X=df.loc[:,col])
    return df

In [62]:
numeric_scaling(fifa_train_x,col_num)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,Right,High/ Medium,RW,Forward,18,2019,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,Left,High/ Medium,LCB,Defender,18,2019,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,Left,High/ Low,LW,Forward,11,2020,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2020,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,Right,High/ Low,ST,Forward,47,2022,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,Left,Medium/ Medium,CB,Defender,55,2022,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,Right,Medium/ Medium,ST,Forward,24,2020,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,Right,High/ Medium,ST,Forward,14,2019,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,Right,Medium/ Medium,RB,Defender,17,2019,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,Left,Medium/ Medium,LWB,Defender,24,2021,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [63]:
numeric_scaling(fifa_test_x,col_num)

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,Right,Medium/ High,CDM,Defender,10,2019,5'9,-0.867562,172,0.135107,0.697853,Medium,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,Left,Medium/ Medium,LB,Defender,20,2021,5'10,-0.491383,163,0.603083,1.715902,Medium,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,Right,High/ Medium,RW,Forward,18,2021,6'1,0.637152,170,-0.301141,-0.320196,High,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,Right,High/ High,LM,Midfielder,7,2023,6'0,0.260974,143,5.266978,4.495960,High,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,Right,Medium/ Medium,CB,Defender,15,2020,6'2,1.013331,170,-0.269414,-0.359352,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,Right,Medium/ Low,LM,Midfielder,11,2020,5'11,-0.115205,172,0.190630,0.502074,Medium,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,Right,Medium/ Medium,CDM,Defender,14,2019,5'11,-0.115205,143,-0.364754,-0.320196,Medium,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,Right,Medium/ Medium,RB,Defender,54,2019,5'10,-0.491383,154,-0.354443,-0.241885,Medium,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,Right,High/ Low,LM,Midfielder,31,2019,5'9,-0.867562,174,-0.134573,-0.006950,High,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,Right,Medium/ Medium,LM,Midfielder,18,2021,5'6,-1.996097,137,-0.158369,-0.046106,Medium,Medium

In [64]:
###
#명목형 데이터 labeling

In [65]:
fifa_train_x.Contract_Valid_Until.unique()

array([2019, 2020, 2022, 2021, 2018, 2023, 2024, 2025, 2026], dtype=int64)

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
def label_encoding(df, param):
    le = LabelEncoder()
    df.loc[:,param] = le.fit_transform(df.loc[:,param])
    return df

In [68]:
label_encoding(fifa_train_x, "Contract_Valid_Until")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,Right,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,Left,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,Left,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,Right,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,Right,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,Left,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,Right,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,Right,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,Right,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,Left,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [69]:
label_encoding(fifa_test_x, "Contract_Valid_Until")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,Right,Medium/ High,CDM,Defender,10,1,5'9,-0.867562,172,0.135107,0.697853,Medium,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,Left,Medium/ Medium,LB,Defender,20,3,5'10,-0.491383,163,0.603083,1.715902,Medium,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,Right,High/ Medium,RW,Forward,18,3,6'1,0.637152,170,-0.301141,-0.320196,High,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,Right,High/ High,LM,Midfielder,7,5,6'0,0.260974,143,5.266978,4.495960,High,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,Right,Medium/ Medium,CB,Defender,15,2,6'2,1.013331,170,-0.269414,-0.359352,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,Right,Medium/ Low,LM,Midfielder,11,2,5'11,-0.115205,172,0.190630,0.502074,Medium,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,Right,Medium/ Medium,CDM,Defender,14,1,5'11,-0.115205,143,-0.364754,-0.320196,Medium,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,Right,Medium/ Medium,RB,Defender,54,1,5'10,-0.491383,154,-0.354443,-0.241885,Medium,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,Right,High/ Low,LM,Midfielder,31,1,5'9,-0.867562,174,-0.134573,-0.006950,High,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,Right,Medium/ Medium,LM,Midfielder,18,3,5'6,-1.996097,137,-0.158369,-0.046106,Medium,Medium

In [70]:
label_encoding(fifa_test_x, "Preferred_Foot")
label_encoding(fifa_train_x, "Preferred_Foot")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,High,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,High,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,High,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,Medium,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,High,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,Medium,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,Medium,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,High,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,Medium,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,Medium,Medium

In [71]:
##work_rate handle

In [72]:
def handle_work_rate(df, param):
    df.loc[:,param] = df.loc[:,param].apply(lambda x: 2 if x=="High" else (1 if x=="Medium" else (0 if x=="Low" else x)))
    return df

In [73]:
fifa_train_x.Attack_Work_Rate.value_counts()

Medium    2426
High       997
Low        177
Name: Attack_Work_Rate, dtype: int64

In [74]:
handle_work_rate(fifa_train_x, "Attack_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,2,Medium
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,2,Medium
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,2,Low
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,1,Medium
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,2,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,1,Medium
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,1,Medium
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,2,Medium
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,1,Medium
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,1,Medium

In [75]:
fifa_train_x.Attack_Work_Rate.value_counts()

1    2426
2     997
0     177
Name: Attack_Work_Rate, dtype: int64

In [76]:
fifa_test_x.Attack_Work_Rate.value_counts()

Medium    1634
High       663
Low        103
Name: Attack_Work_Rate, dtype: int64

In [77]:
handle_work_rate(fifa_test_x, "Attack_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,137351,1.901605,Germany,1.815131,FCAugsburg,1,Medium/ High,CDM,Defender,10,1,5'9,-0.867562,172,0.135107,0.697853,1,High
1,207707,0.825174,Brazil,1.531517,OlympiqueLyonnais,0,Medium/ Medium,LB,Defender,20,3,5'10,-0.491383,163,0.603083,1.715902,1,Medium
2,242101,-0.681829,KoreaRepublic,-0.311976,PohangSteelers,1,High/ Medium,RW,Forward,18,3,6'1,0.637152,170,-0.301141,-0.320196,2,Medium
3,200104,-0.035971,KoreaRepublic,2.524167,TottenhamHotspur,1,High/ High,LM,Midfielder,7,5,6'0,0.260974,143,5.266978,4.495960,2,High
4,244229,-0.251257,Italy,-0.028361,Cittadella,1,Medium/ Medium,CB,Defender,15,2,6'2,1.013331,170,-0.269414,-0.359352,1,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,177922,1.040460,Poland,0.964288,HullCity,1,Medium/ Low,LM,Midfielder,11,2,5'11,-0.115205,172,0.190630,0.502074,1,Low
2396,245525,1.471033,Sudan,-0.879204,AlHazem,1,Medium/ Medium,CDM,Defender,14,1,5'11,-0.115205,143,-0.364754,-0.320196,1,Medium
2397,227949,-0.251257,Scotland,-1.730047,BrightonHoveAlbion,1,Medium/ Medium,RB,Defender,54,1,5'10,-0.491383,154,-0.354443,-0.241885,1,Medium
2398,176773,1.255747,Sweden,0.538867,AkhisarBelediyespor,1,High/ Low,LM,Midfielder,31,1,5'9,-0.867562,174,-0.134573,-0.006950,2,Low
2399,232512,1.040460,Japan,0.680674,SanfrecceHiroshima,1,Medium/ Medium,LM,Midfielder,18,3,5'6,-1.996097,137,-0.158369,-0.046106,1,Medium

In [78]:
fifa_test_x.Attack_Work_Rate.value_counts()

1    1634
2     663
0     103
Name: Attack_Work_Rate, dtype: int64

In [79]:
handle_work_rate(fifa_test_x, "Defence_Work_Rate")
handle_work_rate(fifa_train_x, "Defence_Work_Rate")

,ID,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Position_Class,Jersey_Number,Contract_Valid_Until,Height,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,190972,-0.251299,Argentina,2.156933,SLBenfica,1,High/ Medium,RW,Forward,18,1,5'8,-1.276671,170.0,3.261035,0.493504,2,1
1,179646,0.830590,Denmark,-0.016299,AarhusGF,0,High/ Medium,LCB,Defender,18,1,6'0,0.251133,179.0,-0.379257,-0.271619,2,1
2,225440,-0.467677,GuineaBissau,0.273465,Palermo,0,High/ Low,LW,Forward,11,2,5'9,-0.894720,163.0,-0.241652,-0.373635,2,0
3,212642,-0.684055,Sweden,-0.740710,IFBrommapojkarna,1,Medium/ Medium,LW,Forward,10,2,5'10,-0.512769,154.0,-0.398672,-0.424643,1,1
4,245804,-1.549566,Turkey,-1.320238,Alanyaspor,1,High/ Low,ST,Forward,47,4,5'10,-0.512769,132.0,-0.383961,-0.424643,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,244272,-0.467677,Croatia,-0.306064,DinamoZagreb,0,Medium/ Medium,CB,Defender,55,4,6'6,2.542839,185.0,-0.331721,-0.424643,1,1
3596,201891,0.614213,Austria,-0.161181,TSVHartberg,1,Medium/ Medium,ST,Forward,24,2,5'10,-0.512769,170.0,-0.361944,-0.322627,1,1
3597,241918,-0.467677,Norway,-1.175356,RanheimFotball,1,High/ Medium,ST,Forward,14,1,6'0,0.251133,163.0,-0.419288,-0.424643,2,1
3598,186823,1.696102,Portugal,-0.161181,CDAves,1,Medium/ Medium,RB,Defender,17,1,5'10,-0.512769,161.0,-0.397672,-0.322627,1,1
3599,240328,-0.684055,SaudiArabia,-1.175356,AlFayha,0,Medium/ Medium,LWB,Defender,24,3,5'10,-0.512769,154.0,-0.410281,-0.373635,1,1

In [80]:
#one hot encoding

In [81]:
from sklearn.preprocessing import OneHotEncoder

In [82]:
ohe = OneHotEncoder(sparse=False, handle_unknown="ignore")

In [83]:
result = ohe.fit_transform(fifa_train_x.loc[:,["Position","Position_Class"]])

C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)

In [84]:
result.shape

(3600, 31)

In [85]:
ohe.categories_[0]

array(['CAM', 'CB', 'CDM', 'CF', 'CM', 'GK', 'LAM', 'LB', 'LCB', 'LCM',
       'LDM', 'LF', 'LM', 'LS', 'LW', 'LWB', 'RAM', 'RB', 'RCB', 'RCM',
       'RDM', 'RF', 'RM', 'RS', 'RW', 'RWB', 'ST'], dtype=object)

In [86]:
position_list = ["Position_"+x for x in ohe.categories_[0]]

In [87]:
position_class_list = ["Position_Class"+x for x in ohe.categories_[1]]

In [88]:
position_columns = position_list+position_class_list

In [89]:
fifa_train_x_position_ohe = pd.DataFrame(data=result, columns=position_columns)

In [90]:
test_result = ohe.transform(fifa_test_x.loc[:,["Position","Position_Class"]])

C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)

In [91]:
fifa_test_x_position_ohe = pd.DataFrame(data=test_result, columns=position_columns)

In [92]:
fifa_test_x_position_ohe

,Position_CAM,Position_CB,Position_CDM,Position_CF,Position_CM,Position_GK,Position_LAM,Position_LB,Position_LCB,Position_LCM,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2396,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [93]:
#변수 정리

In [94]:
drop_col = ['Nationality', 'Jersey_Number', 'Club', 'ID','Work_Rate', "Height", "Position", "Position_Class"]

In [95]:
fifa_train_x_sub = fifa_train_x.drop(columns=drop_col)

In [96]:
fifa_train_x_sub

,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate
0,-0.251299,2.156933,1,1,-1.276671,170.0,3.261035,0.493504,2,1
1,0.830590,-0.016299,0,1,0.251133,179.0,-0.379257,-0.271619,2,1
2,-0.467677,0.273465,0,2,-0.894720,163.0,-0.241652,-0.373635,2,0
3,-0.684055,-0.740710,1,2,-0.512769,154.0,-0.398672,-0.424643,1,1
4,-1.549566,-1.320238,1,4,-0.512769,132.0,-0.383961,-0.424643,2,0
...,...,...,...,...,...,...,...,...,...,...
3595,-0.467677,-0.306064,0,4,2.542839,185.0,-0.331721,-0.424643,1,1
3596,0.614213,-0.161181,1,2,-0.512769,170.0,-0.361944,-0.322627,1,1
3597,-0.467677,-1.175356,1,1,0.251133,163.0,-0.419288,-0.424643,2,1
3598,1.696102,-0.161181,1,1,-0.512769,161.0,-0.397672,-0.322627,1,1
3599,-0.684055,-1.175356,0,3,-0.512769,154.0,-0.410281,-0.373635,1,1

In [97]:
fifa_train_x_position_ohe

,Position_CAM,Position_CB,Position_CDM,Position_CF,Position_CM,Position_GK,Position_LAM,Position_LB,Position_LCB,Position_LCM,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [98]:
fifa_train_x_sub = pd.concat([fifa_train_x_sub,fifa_train_x_position_ohe],axis=1)

In [99]:
fifa_train_x_sub

,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
0,-0.251299,2.156933,1,1,-1.276671,170.0,3.261035,0.493504,2,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.830590,-0.016299,0,1,0.251133,179.0,-0.379257,-0.271619,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.467677,0.273465,0,2,-0.894720,163.0,-0.241652,-0.373635,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-0.684055,-0.740710,1,2,-0.512769,154.0,-0.398672,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-1.549566,-1.320238,1,4,-0.512769,132.0,-0.383961,-0.424643,2,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,-0.467677,-0.306064,0,4,2.542839,185.0,-0.331721,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3596,0.614213,-0.161181,1,2,-0.512769,170.0,-0.361944,-0.322627,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3597,-0.467677,-1.175356,1,1,0.251133,163.0,-0.419288,-0.424643,2,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3598,1.696102,-0.161181,1,1,-0.512769,161.0,-0.397672,-0.322627,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3599,-0.684055,-1.175356,0,3,-0.512769,154.0,-0.410281,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [100]:
fifa_test_x_sub = fifa_test_x.drop(columns=drop_col)

In [101]:
fifa_test_x_sub = pd.concat([fifa_test_x_sub,fifa_test_x_position_ohe], axis=1)

In [102]:
fifa_train_x_sub

,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
0,-0.251299,2.156933,1,1,-1.276671,170.0,3.261035,0.493504,2,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.830590,-0.016299,0,1,0.251133,179.0,-0.379257,-0.271619,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.467677,0.273465,0,2,-0.894720,163.0,-0.241652,-0.373635,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-0.684055,-0.740710,1,2,-0.512769,154.0,-0.398672,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-1.549566,-1.320238,1,4,-0.512769,132.0,-0.383961,-0.424643,2,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,-0.467677,-0.306064,0,4,2.542839,185.0,-0.331721,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3596,0.614213,-0.161181,1,2,-0.512769,170.0,-0.361944,-0.322627,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3597,-0.467677,-1.175356,1,1,0.251133,163.0,-0.419288,-0.424643,2,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3598,1.696102,-0.161181,1,1,-0.512769,161.0,-0.397672,-0.322627,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3599,-0.684055,-1.175356,0,3,-0.512769,154.0,-0.410281,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
fifa_train_y

          ID  Value
0     190972  18500
1     179646    500
2     225440   1200
3     212642    325
4     245804    220
...      ...    ...
3595  244272    500
3596  201891    550
3597  241918    170
3598  186823    210
3599  240328    170

[3600 rows x 2 columns]

In [119]:
X_train, X_validation, y_train, y_validation = train_test_split(fifa_train_x_sub, fifa_train_y.drop(columns=["ID"]), train_size=0.7)

In [120]:
X_train

,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
1389,-0.900432,-0.450946,1,3,-2.040574,128.0,-0.331721,-0.220610,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3548,-0.684055,0.852994,1,5,0.251133,168.0,0.629016,0.187455,2,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
487,-0.251299,-0.450946,1,4,0.633084,183.0,-0.360443,-0.322627,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
806,-0.251299,-0.450946,1,3,-0.130818,132.0,-0.375454,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1404,-0.684055,-0.161181,0,2,-0.130818,157.0,-0.281683,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2342,-1.549566,-1.610003,1,1,0.633084,163.0,-0.401374,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3539,2.561613,0.708111,1,1,-0.894720,154.0,-0.321713,-0.067586,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
530,-0.034921,0.852994,1,4,-0.894720,146.0,0.168663,-0.271619,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2823,1.479724,1.432522,1,2,1.015035,181.0,0.398839,2.125767,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2068,-1.333188,-0.595828,0,2,-0.512769,159.0,-0.281683,-0.220610,1,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [121]:
y_train

      Value
1389    600
3548   4900
487     500
806     500
1404    800
...     ...
2342    160
3539    800
530    3700
2823   4400
2068    650

[2520 rows x 1 columns]

In [214]:
from sklearn.ensemble import RandomForestRegressor

In [215]:
model = RandomForestRegressor(n_estimators=100,).fit(X=X_train.loc[:,X_validation.columns[0:10]], y=y_train)

C:\Users\yuvjj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

In [216]:
pred = model.predict(X_validation.loc[:,X_validation.columns[0:10]])

C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)

In [217]:
y_validation

      Value
2173    450
1266  10000
523    7000
2147    575
3287    700
...     ...
3442    325
2086   2100
2702    825
2318    190
3282    600

[1080 rows x 1 columns]

In [218]:
pred

array([ 431.4 , 9787.  , 6683.  , ...,  797.65,  189.02,  581.15])

In [169]:
from sklearn.metrics import mean_squared_error as mse

In [170]:
rmse = lambda y_true, y_pred: mse(y_true=y_true, y_pred=y_pred)**0.5

In [219]:
rmse(y_true=y_validation, y_pred=pred)

548.0189153203463

In [172]:
from sklearn.linear_model import LinearRegression

In [132]:
from statsmodels.formula.api import ols

In [209]:
model = LinearRegression().fit(X=X_train.loc[:,X_train.columns[0:10]], y=y_train)

In [212]:
pred = model.predict(X=X_validation.loc[:,X_validation.columns[0:10]])

In [213]:
rmse(y_true=y_validation, y_pred=pred)

509.05991828014703

In [136]:
X_train.columns

Index(['Age', 'Overall', 'Preferred_Foot', 'Contract_Valid_Until', 'Height_cm',
       'Weight_lb', 'Release_Clause', 'Wage', 'Attack_Work_Rate',
       'Defence_Work_Rate', 'Position_CAM', 'Position_CB', 'Position_CDM',
       'Position_CF', 'Position_CM', 'Position_GK', 'Position_LAM',
       'Position_LB', 'Position_LCB', 'Position_LCM', 'Position_LDM',
       'Position_LF', 'Position_LM', 'Position_LS', 'Position_LW',
       'Position_LWB', 'Position_RAM', 'Position_RB', 'Position_RCB',
       'Position_RCM', 'Position_RDM', 'Position_RF', 'Position_RM',
       'Position_RS', 'Position_RW', 'Position_RWB', 'Position_ST',
       'Position_ClassDefender', 'Position_ClassForward',
       'Position_ClassGoalKeeper', 'Position_ClassMidfielder'],
      dtype='object')

In [138]:
"+".join(X_train.columns)

'Age+Overall+Preferred_Foot+Contract_Valid_Until+Height_cm+Weight_lb+Release_Clause+Wage+Attack_Work_Rate+Defence_Work_Rate+Position_CAM+Position_CB+Position_CDM+Position_CF+Position_CM+Position_GK+Position_LAM+Position_LB+Position_LCB+Position_LCM+Position_LDM+Position_LF+Position_LM+Position_LS+Position_LW+Position_LWB+Position_RAM+Position_RB+Position_RCB+Position_RCM+Position_RDM+Position_RF+Position_RM+Position_RS+Position_RW+Position_RWB+Position_ST+Position_ClassDefender+Position_ClassForward+Position_ClassGoalKeeper+Position_ClassMidfielder'

In [139]:
y_train.Value

1389     600
3548    4900
487      500
806      500
1404     800
        ...
2342     160
3539     800
530     3700
2823    4400
2068     650
Name: Value, Length: 2520, dtype: int64

In [207]:
X_train.columns[0:10]

Index(['Age', 'Overall', 'Preferred_Foot', 'Contract_Valid_Until', 'Height_cm',
       'Weight_lb', 'Release_Clause', 'Wage', 'Attack_Work_Rate',
       'Defence_Work_Rate'],
      dtype='object')

In [151]:
form = "Value"+"~"+"+".join(X_train.columns)

In [152]:
form

'Value~Age+Overall+Preferred_Foot+Contract_Valid_Until+Height_cm+Weight_lb+Release_Clause+Wage+Attack_Work_Rate+Defence_Work_Rate+Position_CAM+Position_CB+Position_CDM+Position_CF+Position_CM+Position_GK+Position_LAM+Position_LB+Position_LCB+Position_LCM+Position_LDM+Position_LF+Position_LM+Position_LS+Position_LW+Position_LWB+Position_RAM+Position_RB+Position_RCB+Position_RCM+Position_RDM+Position_RF+Position_RM+Position_RS+Position_RW+Position_RWB+Position_ST+Position_ClassDefender+Position_ClassForward+Position_ClassGoalKeeper+Position_ClassMidfielder'

In [153]:
pd.concat([X_train,y_train],axis=1)

,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,Defence_Work_Rate,...,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder,Value
1389,-0.900432,-0.450946,1,3,-2.040574,128.0,-0.331721,-0.220610,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,600
3548,-0.684055,0.852994,1,5,0.251133,168.0,0.629016,0.187455,2,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,4900
487,-0.251299,-0.450946,1,4,0.633084,183.0,-0.360443,-0.322627,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,500
806,-0.251299,-0.450946,1,3,-0.130818,132.0,-0.375454,-0.424643,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,500
1404,-0.684055,-0.161181,0,2,-0.130818,157.0,-0.281683,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2342,-1.549566,-1.610003,1,1,0.633084,163.0,-0.401374,-0.373635,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,160
3539,2.561613,0.708111,1,1,-0.894720,154.0,-0.321713,-0.067586,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,800
530,-0.034921,0.852994,1,4,-0.894720,146.0,0.168663,-0.271619,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3700
2823,1.479724,1.432522,1,2,1.015035,181.0,0.398839,2.125767,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4400
2068,-1.333188,-0.595828,0,2,-0.512769,159.0,-0.281683,-0.220610,1,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,650

In [154]:
model2 = ols(formula=form, data=pd.concat([X_train,y_train],axis=1)).fit()

In [155]:
model2.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                        Results: Ordinary least squares
================================================================================
Model:                   OLS                  Adj. R-squared:         0.987
Dependent Variable:      Value                AIC:                    39262.9975
Date:                    2023-04-27 00:21     BIC:                    39478.7821
No. Observations:        2520                 Log-Likelihood:         -19594.
Df Model:                36                   F-statistic:            5439.
Df Residuals:            2483                 Prob (F-statistic):     0.00
R-squared:               0.987                Scale:                  3.3709e+05
--------------------------------------------------------------------------------
                           Coef.   Std.Err.    t     P>|t|    [0.025     0.975]
--------------------------------------------------------------------------------
Intercept                1607.6497 161.5095   9.9539 0.0000  1290.9425 1924.3570
Age                         5.5920  14.5872   0.3833 0.7015   -23.0124   34.1964
Overall                   126.0695  18.7186   6.7350 0.0000    89.3639  162.7752
Preferred_Foot             55.4274  31.6194   1.7530 0.0797    -6.5758  117.4305
Contract_Valid_Until       -3.8712   9.5817  -0.4040 0.6862   -22.6600   14.9177
Height_cm                 -29.0995  19.2782  -1.5095 0.1313   -66.9025    8.7034
Weight_lb                   1.6079   1.2257   1.3118 0.1897    -0.7955    4.0113
Release_Clause           4865.5003  23.1489 210.1830 0.0000  4820.1072 4910.8934
Wage                      155.5486  21.3669   7.2799 0.0000   113.6499  197.4474
Attack_Work_Rate           43.7168  25.2888   1.7287 0.0840    -5.8725   93.3062
Defence_Work_Rate          32.7315  25.2521   1.2962 0.1950   -16.7859   82.2490
Position_CAM              -28.9681  87.3667  -0.3316 0.7402  -200.2872  142.3510
Position_CB                47.1999  44.6373   1.0574 0.2904   -40.3302  134.7301
Position_CDM               23.0997  53.2283   0.4340 0.6643   -81.2768  127.4762
Position_CF               -39.7263 181.8030  -0.2185 0.8270  -396.2275  316.7749
Position_CM               -66.7292  85.3430  -0.7819 0.4344  -234.0800  100.6215
Position_GK               165.7577  34.8807   4.7521 0.0000    97.3595  234.1559
Position_LAM             -253.7089 516.7181  -0.4910 0.6235 -1266.9516  759.5339
Position_LB                70.8518  48.8209   1.4513 0.1468   -24.8822  166.5857
Position_LCB               77.1068  61.2809   1.2583 0.2084   -43.0602  197.2738
Position_LCM              109.9781  99.8369   1.1016 0.2708   -85.7941  305.7502
Position_LDM              -73.7886  88.1025  -0.8375 0.4024  -246.5506   98.9734
Position_LF              -121.3476 302.5697  -0.4011 0.6884  -714.6625  471.9674
Position_LM               -26.4052  87.6246  -0.3013 0.7632  -198.2300  145.4196
Position_LS              -102.0192 114.5488  -0.8906 0.3732  -326.6402  122.6018
Position_LW              -464.2194  99.5235  -4.6644 0.0000  -659.3770 -269.0619
Position_LWB               96.9559 121.8960   0.7954 0.4265  -142.0723  335.9841
Position_RAM              934.9447 266.9176   3.5027 0.0005   411.5408 1458.3487
Position_RB                -8.0752  48.1773  -0.1676 0.8669  -102.5471   86.3967
Position_RCB               57.1032  65.5546   0.8711 0.3838   -71.4441  185.6504
Position_RCM              -98.6536 107.3948  -0.9186 0.3584  -309.2461  111.9390
Position_RDM               85.6268  91.5996   0.9348 0.3500   -93.9927  265.2464
Position_RF              2539.9279 303.2694   8.3752 0.0000  1945.2408 3134.6149
Position_RM              -132.8583  86.8504  -1.5297 0.1262  -303.1650   37.4483
Position_RS              -277.0916 126.3373  -2.1933 0.0284  -524.8289  -29.3542
Position_RW              -420.0946 100.7626  -4.1692 0.0000  -617.6820 -222.5072
Position_RWB              -86.4501 138.7845  -0.6229 0.5334  -358.5955  185.6952
Position_ST              -400.7668  71.1544  -5.6324 0.0000  -540.2950 -261.2387
Position_ClassDefender    289.6302  54.6339   5.3013 0.0000   182.4976  396.7628
Position_ClassForward     714.6623  68.9224  10.3691 0.0000   579.5111  849.8136
Position_ClassGoalKeeper  165.7577  34.8807   4.7521 0.0000    97.3595  234.1559
Position_ClassMidfielder  437.5995  73.2745   5.9721 0.0000   293.9140  581.2849
--------------------------------------------------------------------------------
Omnibus:              1677.514        Durbin-Watson:           2.015
Prob(Omnibus):        0.000           Jarque-Bera (JB):        277440.738
Skew:                 2.153           Prob(JB):                0.000
Kurtosis:             54.223          Condition No.:           33860687430684820
================================================================================
* The condition number is large (3e+16). This might indicate             strong
multicollinearity or other numerical problems.
"""

In [156]:
pred = model2.predict(X_validation)

In [157]:
rmse(y_true=y_validation, y_pred=pred)

515.8311052866298

In [173]:
from sklearn.naive_bayes import GaussianNB

In [174]:
model = GaussianNB().fit(X=X_train, y=y_train)

C:\Users\yuvjj\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [175]:
pred = model.predict(X=X_validation)

In [176]:
rmse(y_true=y_validation, y_pred=pred)

3183.6975758745725

In [177]:
from sklearn.neighbors import KNeighborsRegressor

In [190]:
model = KNeighborsRegressor(n_neighbors=2).fit(X=X_train, y=y_train)

In [191]:
pred = model.predict(X=X_validation)

In [192]:
rmse(y_true=y_validation, y_pred=pred)

1871.5602506974603

In [262]:
from patsy import dmatrices

In [263]:
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

In [264]:
y, X = dmatrices(formula_like=form, data=pd.concat([X_train,y_train],axis=1), return_type="dataframe")

In [265]:
y

       Value
1389   600.0
3548  4900.0
487    500.0
806    500.0
1404   800.0
...      ...
2342   160.0
3539   800.0
530   3700.0
2823  4400.0
2068   650.0

[2520 rows x 1 columns]

In [266]:
X

,Intercept,Age,Overall,Preferred_Foot,Contract_Valid_Until,Height_cm,Weight_lb,Release_Clause,Wage,Attack_Work_Rate,...,Position_RF,Position_RM,Position_RS,Position_RW,Position_RWB,Position_ST,Position_ClassDefender,Position_ClassForward,Position_ClassGoalKeeper,Position_ClassMidfielder
1389,1.0,-0.900432,-0.450946,1.0,3.0,-2.040574,128.0,-0.331721,-0.220610,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3548,1.0,-0.684055,0.852994,1.0,5.0,0.251133,168.0,0.629016,0.187455,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
487,1.0,-0.251299,-0.450946,1.0,4.0,0.633084,183.0,-0.360443,-0.322627,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
806,1.0,-0.251299,-0.450946,1.0,3.0,-0.130818,132.0,-0.375454,-0.424643,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1404,1.0,-0.684055,-0.161181,0.0,2.0,-0.130818,157.0,-0.281683,-0.373635,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2342,1.0,-1.549566,-1.610003,1.0,1.0,0.633084,163.0,-0.401374,-0.373635,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3539,1.0,2.561613,0.708111,1.0,1.0,-0.894720,154.0,-0.321713,-0.067586,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
530,1.0,-0.034921,0.852994,1.0,4.0,-0.894720,146.0,0.168663,-0.271619,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2823,1.0,1.479724,1.432522,1.0,2.0,1.015035,181.0,0.398839,2.125767,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2068,1.0,-1.333188,-0.595828,0.0,2.0,-0.512769,159.0,-0.281683,-0.220610,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [273]:
df_vif = pd.DataFrame()

In [274]:
df_vif["columns"]=X.columns

In [275]:
len(X.columns)

42

In [276]:
X.shape[1]

42

In [277]:
df_vif

                     columns
0                  Intercept
1                        Age
2                    Overall
3             Preferred_Foot
4       Contract_Valid_Until
5                  Height_cm
6                  Weight_lb
7             Release_Clause
8                       Wage
9           Attack_Work_Rate
10         Defence_Work_Rate
11              Position_CAM
12               Position_CB
13              Position_CDM
14               Position_CF
15               Position_CM
16               Position_GK
17              Position_LAM
18               Position_LB
19              Position_LCB
20              Position_LCM
21              Position_LDM
22               Position_LF
23               Position_LM
24               Position_LS
25               Position_LW
26              Position_LWB
27              Position_RAM
28               Position_RB
29              Position_RCB
30              Position_RCM
31              Position_RDM
32               Position_RF
33               Position_RM
34               Position_RS
35               Position_RW
36              Position_RWB
37               Position_ST
38    Position_ClassDefender
39     Position_ClassForward
40  Position_ClassGoalKeeper
41  Position_ClassMidfielder

In [278]:
range(len(X.columns))

range(0, 42)

In [279]:
X.values.shape

(2520, 42)

In [252]:
import numpy as np

In [280]:
df_vif["vif"]=[vif(X.values,i) for i in range(len(X.columns))]

In [281]:
len(df_vif)

42

In [282]:
df_vif

                     columns       vif
0                  Intercept  0.000000
1                        Age  1.594398
2                    Overall  2.633487
3             Preferred_Foot  1.343354
4       Contract_Valid_Until  1.179436
5                  Height_cm  2.744800
6                  Weight_lb  2.594985
7             Release_Clause  4.036537
8                       Wage  3.454101
9           Attack_Work_Rate  1.314835
10         Defence_Work_Rate  1.199004
11              Position_CAM       inf
12               Position_CB       inf
13              Position_CDM       inf
14               Position_CF       inf
15               Position_CM       inf
16               Position_GK       inf
17              Position_LAM       inf
18               Position_LB       inf
19              Position_LCB       inf
20              Position_LCM       inf
21              Position_LDM       inf
22               Position_LF       inf
23               Position_LM       inf
24               Position_LS       inf
25               Position_LW       inf
26              Position_LWB       inf
27              Position_RAM       inf
28               Position_RB       inf
29              Position_RCB       inf
30              Position_RCM       inf
31              Position_RDM       inf
32               Position_RF       inf
33               Position_RM       inf
34               Position_RS       inf
35               Position_RW       inf
36              Position_RWB       inf
37               Position_ST       inf
38    Position_ClassDefender       inf
39     Position_ClassForward       inf
40  Position_ClassGoalKeeper       inf
41  Position_ClassMidfielder       inf